![](https://www.paho.org/sites/default/files/styles/max_1500x1500/public/banner-covid-19-1280x549.jpg?itok=R7z_5No5)

# Análisis del COVID-19 en Colombia
## Trabajo final: Analisis Predictivo y gestión de datos**


***Presentado Por:***
- *Paula Andrea Solano Pardo*
- *Jenssy Johanna Garces Parra*
- *Ingrid Alexandra Aponte Caro*

**Paso 1**:

Importar las librerias que vamos a utilizar en el desarrollo del ejercicio. En este caso, importamos en primer lugar Pandas para la administración de las bases de datos, seguido de matplotlib que no ayuda con las graficas.

In [5]:
import pandas as pd
import matplotlib.pyplot as plt

**Paso 2:**

Cargar la base de datos que vamos a utilizar para el desarrollo del ejercicio, en este caso, utilizamos una base de datos relacionadas en la página "Datos abiertos Colombia" que contine información a cerca del COVID- 19. esta base se carga directamente desde la página de internet.

La base, tiene 6,39 millones de filas y 23 columnas, en las que se presenta la siguiente información:

- Fecha_reporte_web	

- Id_de_caso	fecha_de_notificaci_n	

- Departamento	

- Departamento_nom	

- Ciudad_municipio

- Ciudad_municipio_nom	

- Edad	

- Unidad_medida	

- Sexo

- Tipo de contagio

- Ubicación del caso

- Estado

- Código ISO del país

- Nombre del país

In [7]:
url_csv = 'https://www.datos.gov.co/resource/gt2j-8ykr.json'
df = pd.read_json(url_csv)
df.head()

,fecha_reporte_web,id_de_caso,fecha_de_notificaci_n,departamento,departamento_nom,ciudad_municipio,ciudad_municipio_nom,edad,unidad_medida,sexo,...,ubicacion,estado,recuperado,fecha_inicio_sintomas,fecha_diagnostico,fecha_recuperado,tipo_recuperacion,per_etn_,fecha_muerte,nom_grupo_
0,2020-12-24 00:00:00,1556979,2020-12-22 00:00:00,76,VALLE,76001,CALI,67,1,F,...,Casa,Leve,Recuperado,2020-12-21 00:00:00,2020-12-23 00:00:00,2021-01-04 00:00:00,Tiempo,6,NaN,NaN
1,2020-12-24 00:00:00,1556980,2020-12-19 00:00:00,76,VALLE,76001,CALI,66,1,F,...,Casa,Leve,Recuperado,2020-12-07 00:00:00,2020-12-23 00:00:00,2020-12-25 00:00:00,Tiempo,6,NaN,NaN
2,2020-12-24 00:00:00,1556981,2020-12-19 00:00:00,76,VALLE,76001,CALI,68,1,F,...,Casa,Leve,Recuperado,2020-12-18 00:00:00,2020-12-22 00:00:00,2021-01-01 00:00:00,Tiempo,6,NaN,NaN
3,2020-12-24 00:00:00,1556982,2020-12-22 00:00:00,76,VALLE,76001,CALI,74,1,F,...,Fallecido,Fallecido,Fallecido,2020-12-17 00:00:00,2020-12-23 00:00:00,NaN,NaN,6,2020-12-30 00:00:00,NaN
4,2020-12-24 00:00:00,1556983,2020-12-22 00:00:00,76,VALLE,76001,CALI,65,1,F,...,Casa,Leve,Recuperado,2020-12-21 00:00:00,2020-12-23 00:00:00,2021-01-04 00:00:00,Tiempo,6,NaN,NaN

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   fecha_reporte_web      1000 non-null   object
 1   id_de_caso             1000 non-null   int64
 2   fecha_de_notificaci_n  1000 non-null   object
 3   departamento           1000 non-null   int64
 4   departamento_nom       1000 non-null   object
 5   ciudad_municipio       1000 non-null   int64
 6   ciudad_municipio_nom   1000 non-null   object
 7   edad                   1000 non-null   int64
 8   unidad_medida          1000 non-null   int64
 9   sexo                   1000 non-null   object
 10  fuente_tipo_contagio   1000 non-null   object
 11  ubicacion              1000 non-null   object
 12  estado                 1000 non-null   object
 13  recuperado             1000 non-null   object
 14  fecha_inicio_sintomas  988 non-null    object
 15  fecha_diagnostico      1000 non-null   object
 16  fecha_recuperado       960 non-null    object
 17  tipo_recuperacion      960 non-null    object
 18  per_etn_               1000 non-null   int64
 19  fecha_muerte           42 non-null     object
 20  nom_grupo_             13 non-null     object
dtypes: int64(6), object(15)
memory usage: 164.2+ KB